import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// pages
import Welcome from './welcome'
import Services from './services'
import Plans from './plans'
import Clients from './clients'
import Contact from './contact'

export default function Main() {
  return (
    <>
      <Head>
        <title>Dietitian Arti | Finest Diets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="fullpage ">
        <Welcome></Welcome>
      </div>
      <div className="fullpage">
        <Services></Services>
      </div>

      <div className="fullpage">
        <Plans></Plans>
      </div>

      <div className="fullpage">
        <Clients></Clients>
      </div>

      <div className="fullpage">
        <Contact></Contact>
      </div>
    </>
  )
}
