import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// pages
import Welcome from './welcome'
import Services from './services'
import Plans from './plans'
import Clients from './clients'
import Contact from './contact'

export default function Main() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="./font/Gatwick-Bold.otf"
          rel="preload"
          as="font"
          crossOrigin=""
        />
      </Head>
      <div className="homepage">
        <Welcome></Welcome>
      </div>
      <Services></Services>
      <Plans></Plans>
      <Clients></Clients>
      <div className="homepage">
        <Contact></Contact>
      </div>
    </>
  )
}
